name: QEMU

on: [push, workflow_dispatch]

jobs:
  unit:
    name: QEMU
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        arch:
          - 386
          - amd64
          - arm
          - arm64
          - ppc64
          - ppc64le
          - riscv64
          - s390x
          - riscv64
    steps:
      - run: git config --global core.autocrlf false
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - run: |
          sudo add-apt-repository -y ppa:canonical-server/server-backports
          sudo apt -y update
          sudo apt -y install qemu-user
      - name: Docker run
        run: make ${{ matrix.arch }}
